# Generated by Django 3.0.7 on 2020-06-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_artist_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_string',
            field=models.CharField(default='text', max_length=255),
            preserve_default=False,
        ),
    ]
